### ISSUE TITLE
抱歉用精简版 py3.10环境编译各种报错

### ISSUE THREAD

**Issue by Chinakentgao** [MrWQ/HanGuang#1]
我requirements.txt 里面已经全部安装了还是报错不知道什么问题了
setup.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import setup
running py2exe

  13 missing Modules
  ------------------
? __main__                            imported from bdb, pdb
? _frozen_importlib                   imported from importlib, importlib.abc, zipimport
? _frozen_importlib_external          imported from importlib, importlib._bootstrap, importlib.abc, zipimport
? _posixshmem                         imported from multiprocessing.resource_tracker, multiprocessing.shared_memory
? _winreg                             imported from platform
? asyncio.DefaultEventLoopPolicy      imported from -
? dummy.Process                       imported from multiprocessing.pool
? java.lang                           imported from platform
? org.python.core                     imported from copy, pickle
? os.path                             imported from ctypes._aix, distutils.file_util, os, pkgutil, py_compile, sysconfig, tracemalloc, unittest, unittest.util
? pep517                              imported from importlib.metadata
? readline                            imported from cmd, code, pdb
? resource                            imported from test.support
Building 'dist\rmker8hi.exe'.
error: [WinError 87] 参数错误。

[-] py2exe打包出错了-_-

[+] successfully! F:\hanGuang_V0.4\rmker8hi.exe

88 INFO: PyInstaller: 4.3
88 INFO: Python: 3.10.1
104 INFO: Platform: Windows-10-10.0.19042-SP0
105 INFO: wrote C:\Users\39485\AppData\Local\Temp\xtvk4z0q0.spec
108 INFO: UPX is not available.
113 INFO: Extending PYTHONPATH with paths
['C:\\Users\\39485\\AppData\\Local\\Temp',
 'C:\\Users\\39485\\AppData\\Local\\Temp']
120 INFO: checking Analysis
120 INFO: Building Analysis because Analysis-00.toc is non existent
121 INFO: Initializing module dependency graph...
125 INFO: Caching module graph hooks...
137 WARNING: Several hooks defined for module 'win32ctypes.core'. Please take care they do not conflict.
141 INFO: Analyzing base_library.zip ...
3868 INFO: Processing pre-find module path hook distutils from 'F:\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
3868 INFO: distutils: retargeting to non-venv dir 'F:\\Python310\\lib'
Traceback (most recent call last):
  File "F:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "F:\Python310\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "F:\Python310\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "F:\Python310\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "F:\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 737, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "F:\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 684, in build
    exec(code, spec_namespace)
  File "C:\Users\39485\AppData\Local\Temp\xtvk4z0q0.spec", line 7, in <module>
    a = Analysis(['C:\\Users\\39485\\AppData\\Local\\Temp\\xtvk4z0q0.py'],
  File "F:\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 242, in __init__
    self.__postinit__()
  File "F:\Python310\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "F:\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 341, in assemble
    self.graph = initialize_modgraph(
  File "F:\Python310\lib\site-packages\PyInstaller\depend\analysis.py", line 804, in initialize_modgraph
    graph = PyiModuleGraph(
  File "F:\Python310\lib\site-packages\PyInstaller\depend\analysis.py", line 120, in __init__
    self._analyze_base_modules()
  File "F:\Python310\lib\site-packages\PyInstaller\depend\analysis.py", line 288, in _analyze_base_modules
    self._base_modules = [mod
  File "F:\Python310\lib\site-packages\PyInstaller\depend\analysis.py", line 290, in <listcomp>
    for mod in self.import_hook(req)]
  File "F:\Python310\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1497, in import_hook
    target_package, target_module_partname = self._find_head_package(
  File "F:\Python310\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1703, in _find_head_package
    raise ImportError("No module named " + target_package_name)
ImportError: No module named _bootlocale

[-] pyinstaller打包出错了-_-

**Comment by MrWQ** [comment]
推荐环境是3.7.5
建议在win7虚拟机中操作

**Comment by Chinakentgao** [comment]
这么苛刻的吗？ 还得换环境麻烦死- -
